温度センサ関数を追加しました
toasahi/karuvege pull request #8
Opened 2022-12-08 03:35 UTC by welson510

2022-12-09 00:35 UTC, toasahi requested changes
変更して欲しい点があります

2022-12-09 00:35 UTC, toasahi commented on Karuvege.ino
> +int reading;
変数名を変更してください
readingではなく、tempAnalogReadingなどに変更して意味が伝わるようにしてください

2022-12-09 00:35 UTC, toasahi commented on Karuvege.ino
> +  temp(); //温度センサ関数
関数名がtempだと初めて読んだ人が何の関数かわからないので,getTemperature()などデータを取得することがわかるようにしてください

2022-12-09 00:35 UTC, toasahi commented on Karuvege.ino
> +int temprature;
英語の綴りが間違っています
temperature

2022-12-09 00:35 UTC, toasahi commented on Karuvege.ino
>  }
可能ならば、GetData.ino GetData.hに関数を分割できると嬉しいです

2022-12-15 01:55 UTC, welson510 commented on Karuvege.ino
>  }
分割がすぐに修正できなかったので、後々修正したいと思います。

2022-12-15 01:56 UTC, toasahi approved these changes
LGTM!!👍

2022-12-15 01:56 UTC, merged